# config.yaml

project:
  name: "BDA"
  version: "1.0.0"
  api_version: "/api/v1"

paths:
  base_dir: null  # Will be set programmatically
  faiss_index_dir: "vector_stores/faiss_index"
  vector_store_dir: "vector_stores"

llm:
  provider: "google"
  model_name: "gemini-1.5-flashu"
  temperature: 0.0
  max_tokens: null
  streaming: true
  additional_params: {}

embedding:
  provider: "huggingface"
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  device: "mps"  # Changed from mps to cpu for container compatibility
  additional_params: {}

vector_store:
  provider: "pgvector"
  collection_name: "chunk_embeddings"

  additional_params: {}

chunking:
  chunk_size: 512
  chunk_overlap: 200

retrieval:
  method: "default" # Options: default, semantic, keyword, hybrid, ensemble, reranked
  k: 5
  # Method-specific parameters
  params:
    # Semantic retrieval parameters
    score_threshold: 0.5
    
    # Hybrid retrieval parameters
    prioritize_semantic: true
    
    # Ensemble retrieval parameters
    weights: [0.7, 0.3]  # Weights for semantic and keyword retrievers
    
    # Reranking parameters
    reranker_model: colbert
    reranker_threshold: 0.7

storage:
  provider: supabase



# Database configuration
database:
  provider: postgres # Options: litedb, sqlite
  additional_params: {}


celery: #REMOVE IF enable_parsers is false
  broker_url: rediss://:AU5MAAIjcDFiYmQxNzhmMjIzMmE0ZGM3OTRkYjRiZTg4MTkxNDJiNXAxMA@selected-tick-20044.upstash.io:6379?ssl_cert_reqs=required
  result_backend: rediss://:AU5MAAIjcDFiYmQxNzhmMjIzMmE0ZGM3OTRkYjRiZTg4MTkxNDJiNXAxMA@selected-tick-20044.upstash.io:6379?ssl_cert_reqs=required