version: "3.9"
name: simba

services:
  server:
    image: ${IMAGE_NAME:-simba}:${IMAGE_TAG:-latest}
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-false}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY:-}
      - DEVICE=${DEVICE:-cpu}
      - OLLAMA_HOST=ollama:11434
      
      - SUPABASE_URL=http://host.docker.internal:8000
      - SUPABASE_JWT_SECRET
      - ANON_KEY
      - SUPABASE_PUBLIC_KEY
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB