FROM python:3.12-slim-bullseye

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# Copy the application into the container.
COPY . /app

# Install the application dependencies.
WORKDIR /app
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      build-essential \
      libpq-dev \
      libgl1-mesa-glx \
      libglib2.0-0 \
 && rm -rf /var/lib/apt/lists/*
RUN uv sync --frozen --no-cache

ARG OPENAI_API_KEY
ARG LANGCHAIN_API_KEY
ARG MISTRAL_API_KEY
ARG REDIS_HOST
ARG CELERY_BROKER_URL
ARG CELERY_RESULT_BACKEND
ARG SUPABASE_URL
ARG SUPABASE_JWT_SECRET
ARG ANON_KEY
ARG SUPABASE_PUBLIC_KEY
ARG POSTGRES_HOST
ARG POSTGRES_PORT
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

EXPOSE 8080
ENTRYPOINT ["/app/entrypoint.sh"]