[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
"langchain>=0.3.13",
"langgraph>=0.2.60",
"python-dotenv>=1.0.1",
"faiss-cpu>=1.9.0.post1",
"langchain-community>=0.3.13",
"langchain-openai>=0.2.14",
"uvicorn>=0.34.0",
"fastapi[standard]>=0.115.12",
"markdown>=3.7",
"unstructured[local-inference]>=0.16.12",
"langchain-chroma>=0.1.4",
"markitdown>=0.0.1a3",
"litellm>=1.56.6",
"python-multipart>=0.0.20",
"pytest>=8.3.4",
"pytest-asyncio>=0.25.2",
"pillow-heif>=0.21.0",
"pdf2image>=1.17.0",
"pdfminer-six>=20240706",
"docling>=2.15.1",
"langchain-docling>=0.2.0",
"ipykernel>=6.29.5",
"ollama>=0.4.6",
"langchain-ollama>=0.2.2",
"rq>=2.1.0",
"pymupdf>=1.25.2",
"rank-bm25>=0.2.2",
"langchain-experimental>=0.3.4",
"sentence-transformers>=3.4.1",
"langchain-huggingface>=0.1.2",
"pydantic-settings>=2.7.1",
"torch>=2.6.0",
"torchvision>=0.21.0",
"torchaudio>=2.6.0",
"celery>=5.4.0",
"mistralai>=1.5.1",
"minio>=7.2.15",
"supabase>=2.15.0",
"sqlalchemy>=2.0.40",
"psycopg2-binary>=2.9.10",
"redis>=5.2.1",
"pgvector>=0.4.1",
"email-validator>=2.2.0",

]
